config/routes.rb
Rails.application.routes.draw do
  

   

  #resources :imprimir_lista
  resources :producto_puestos
  resources :guardias
  resources :puesto_puestos
  resources :turnos

  resources :presupuestooos do
      member do
        get 'imprimir'
    end
  end
  
  resources :categorias
  resources :productos
  resources :control_stock
  resources :stock
  
  resources :puestos do
            member do
            get 'pdf'
          end
        end

  resources :clientes
  
  resources :registro_clientes
  resources :reportes
  resources :presupuesto_creates
  resources :crea_presupuestos
  resources :crear_presupuestos
  
  resources :puesto_registros
  resources :guardia_registros
  resources :presupuestos
  resources :lista_calendarios
  resources :calendarios
  resources :registro_puestos

  get 'lista_puestos/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'guardias#index'

  post 'stock/incStock'

end

app/models/calendario.rb
class Calendario < ApplicationRecord
	validates :diasTrabajados, presence: true

	belongs_to :regis_guardium
	has_many :lista_calendario
	has_many :reporte
end

app/models/categoria.rb
class Categoria < ApplicationRecord
	has_many :productos 
end

app/models/cliente.rb
class Cliente < ApplicationRecord

	#validates :nombre, :num_ruc, :telefono, :direccion, presence: true

	has_many :puestos

	#has_many :reportes

	#paginacion
	self.per_page = 10
end

app/models/control_stock.rb
class ControlStock < ApplicationRecord
end

app/models/guardia.rb
class Guardia < ApplicationRecord
	has_many :puesto_puestos


	self.per_page = 10
end

app/models/presupuestooo.rb
class Presupuestooo < ApplicationRecord
	belongs_to :turno 
end

app/models/producto.rb
class Producto < ApplicationRecord
	belongs_to :categoria
	
	#belongs_to :puesto

	has_many :producto_puestos



end 

app/models/producto_puesto.rb
class ProductoPuesto < ApplicationRecord
	belongs_to :puesto
	belongs_to :producto
end

app/models/puesto.rb
class Puesto < ApplicationRecord
 
	
	#validates :direccion, :turno, :hora_entrada, :hora_salida, :cliente_id, :regis_guardium_id, presence: true


	belongs_to :cliente
	#belongs_to :regis_guardium


	has_many :reportes
	has_many :puesto_puestos
	accepts_nested_attributes_for  :puesto_puestos, allow_destroy: true
	
	has_many :producto_puestos
	accepts_nested_attributes_for  :producto_puestos, allow_destroy: true

	
	#Paginacion
	self.per_page = 10 
end

app/models/puesto_puesto.rb
class PuestoPuesto < ApplicationRecord
	belongs_to :puesto
	belongs_to :guardia
end

app/models/puesto_registro.rb
class PuestoRegistro < ApplicationRecord
	validates :puestoNombre, :direccion, :turno, :horaEntrada, :horaSalida, presence: true

	belongs_to :regis_guardium

	belongs_to :cliente
	has_many :calendario

	self.per_page = 10
end

app/models/regis_guardium.rb
class RegisGuardium < ApplicationRecord
	#validates :nombre, :apellido, :numDocumento, :direccion, :telefono,  presence: true
	

	#has_many :calendario
	
	has_many :puestos

	#has_many :reportes

	self.per_page = 10
end

app/models/registro_puesto.rb
class RegistroPuesto < ApplicationRecord
end

app/models/reporte.rb
class Reporte < ApplicationRecord
	#validates :horaEntrada, :horaSalida, :novedad, presence: true

	#belongs_to :calendario
	belongs_to :puesto
	#belongs_to :cliente
	#belongs_to :regis_guardia
end

app/models/stocks.rb
class Stocks < ApplicationRecord

	# 	validates :producto, :cantidad, :descripcion, presence: true
	#belongs_to :producto

end

app/models/turno.rb
class Turno < ApplicationRecord
	has_many :presupuestooos 
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    
     if params[:search].nil?
      @clientes = Cliente.all
    else
      @clientes = Cliente.where("nombre LIKE ?", "%#{params["search"]}%")
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
    #@cliente = @puesto.cliente.build
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente Creado.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente Actualizado.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :num_ruc, :telefono, :direccion, :estado, :email, :gerente, :rubro, :sucursales, :descripcion, :fechaInicio,)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/guardia_helper.rb
module GuardiaHelper
end

app/helpers/guardias_helper.rb
module GuardiasHelper
end

app/helpers/puestos_helper.rb
module PuestosHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
         
          
                  <b>
                <form class="form-inline">

                <div class="panel panel-info">
                  <div class="panel-heading">Datos Principales</div>
                  <div class="panel-body">
          
                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.text_field :nombre, id: :cliente_nombre, class:"form-control", placeholder:"Cliente" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.text_field :num_ruc, id: :cliente_num_ruc, class:"form-control", placeholder:"Nº Ruc" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.text_field :telefono, id: :cliente_telefono, class:"form-control", placeholder:"Telefono" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">  
                        <div class="field">
                          <%= form.text_field :direccion, id: :cliente_direccion, class:"form-control", placeholder:"Direccion" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.text_field :email, id: :cliente_email, class:"form-control", placeholder:"Correo Electronico" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.text_field :rubro, id: :cliente_rubro, class:"form-control", placeholder:"Rubro" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.text_field :gerente, id: :cliente_gerente, class:"form-control", placeholder:"Gerente/Encargado" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.text_field :sucursales, id: :cliente_sucursales, class:"form-control", placeholder:"Sucrusales" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.text_field :descripcion, id: :cliente_descripcion, class:"form-control", placeholder:"Descripcion" %><br><br>
                        </div>
                      </div>

                      <div class="col-xs-6">
                        <div class="field">
                          <%= form.date_field :fechaInicio, id: :cliente_fechaInicio, class:"form-control", placeholder:"Fecha Inicio" %><br><br>
                        </div>
                      </div>

        
                      <div class="col-xs-3">
                        <div class="field">
                          <%= form.label "Cliente Activo?" %>
                          <%= form.check_box :estado, id: :cliente_estado %>
                        </div>
                      </div>
          <div class="col-xs-2">
          </div>
          <div class="col-xs-3">
          </div>
      </div>
    </div>

        <div class="col-xs-3">
                        <div class="actions">
                          <%= form.submit "Guardar", :class=>"button-guardar"%>
                        </div>
                        <% end %>
        </div>

app/views/clientes/edit.html.erb
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
	        <div class="col-xs-3">
				<h2>Editar Cliente</h2><br><br><br>

			</div>
			<div class="col-xs-6">
			</div>
			<div class="col-xs-3">

				<%= link_to @cliente, class: "btn btn-info" do %> <i class="glyphicon glyphicon-eye-open"></i>  Ver <% end %> |
				<%= link_to clientes_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %> 
			</div>

			<%= render 'form', cliente: @cliente, class: "btn btn-info" do %>
				<% end %>

			</div>
	</div>
</div>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
        <div class="col-xs-3">
            <h2>Registrar Cliente</h2><br><br><br>
        </div>
      
        <div class="col-xs-5">  
            <%= link_to new_cliente_path, class: 'btn btn-success' do %>
            <i class="glyphicon glyphicon-user"></i> 
            <% end %>      
        </div>
        <div class="col-xs-4">
            <%= form_tag clientes_path, :method => 'get' do %>
                <p>
                  <%= text_field_tag :search, params[:search] %>
                  <%= submit_tag "Buscar", :name => nil %>
                </p>
            <% end %>
        </div>

      
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Cliente</th>
                          <th>Nº Ruc</th>
                          <th>Telefono</th>
                          <th>Direccion</th>
                          <th>Correo Elec</th>
                          <th>Rubro</th>
                          <th>Gerente/Encargado</th>
                          <!--<th>Sucursales</th>
                          <th>Descripcion</th> -->
                          <th>Fecha Inicio</th>
                          <th>Estado</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @clientes.each do |cliente| %>
                          <tr>
                            <td><%= cliente.nombre %></td>
                            <td><%= cliente.num_ruc %></td>
                            <td><%= cliente.telefono %></td>
                            <td><%= cliente.direccion %></td>
                            <td><%= cliente.email %></td>
                            <td><%= cliente.rubro %></td>
                            <td><%= cliente.gerente %></td>
                            <!--<td><%= cliente.sucursales %></td>
                            <td><%= cliente.descripcion %></td> -->
                            <td><%= cliente.fechaInicio %></td>
                            <td><%= cliente.estado %></td>

                            
                            <td><%= link_to cliente, class: 'btn btn-info' do %>
                                  <i class="glyphicon glyphicon-eye-open"></i> Ver Más<% end %> 
                            </td>

                            <td><%= link_to edit_cliente_path(cliente), class: 'btn btn-info' do %>
                                <i class="glyphicon glyphicon-edit"></i> Editar <% end %>
                            </td>

                            <td><%= link_to cliente, method: :delete, data: { confirm: 'Estas seguro de Eliminar?' }, class: 'btn btn-primary' do %>
                                      <i class="glyphicon glyphicon-trash"></i> Eliminar <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                </div>

                  </div>
              </div>
            </div>
          </div>

          <div class="col-xs-3">
            
          </div>

          <div class="col-xs-5">
          </div>       
</div> 

</div>
</div>
</div>

app/views/clientes/new.html.erb
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
	        <div class="col-xs-3">
				<h2>Nuevo Cliente</h2><br><br><br>
			</div>
		</div>


				<%= render 'form', cliente: @cliente %>
		<div class="col-xs-5">
        </div>
        <div class="col-xs-4">
        	<%= link_to clientes_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %>
				
		</div>
		</div>
</div>

				

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>
<div id="main-container" class="container">
      <div class="row"><br><br>
      <div class="col-xs-12">
          <div class="col-xs-6">
          </div>

          <div class="col-xs-6">
                   <%= link_to edit_cliente_path(@cliente), class: "btn btn-info" do %><i class="glyphicon glyphicon-pencil"></i> Editar <% end %> |
                    <%= link_to clientes_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %>

          </div>
          <br><br><br><br>
          <div class="col-xs-10">
            <table class="table table-striped">
              <tbody>
                <tr>
                  <td><p>
                    <strong>Nombre:</strong>
                    <%= @cliente.nombre %>
                  </p></td>

                  <td><p>
                    <strong>Num ruc:</strong>
                    <%= @cliente.num_ruc %>
                  </p></td>

                  <td><p>
                    <strong>Telefono:</strong>
                    <%= @cliente.telefono %>
                  </p></td>

                  <td><p>
                    <strong>Direccion:</strong>
                    <%= @cliente.direccion %>
                  </p></td>

                   <td><p>
                    <strong>Correo Elec:</strong>
                    <%= @cliente.email %>
                  </p></td>

              </tr>
                <br>
                <tr>

                   <td><p>
                    <strong>Rubro:</strong>
                    <%= @cliente.rubro %>
                  </p></td>

                   <td><p>
                    <strong>Gerente/Encargado:</strong>
                    <%= @cliente.gerente %>
                  </p></td>

                   <td><p>
                    <strong>Sucursales:</strong>
                    <%= @cliente.sucursales %>
                  </p></td>

                   <td><p>
                    <strong>Descripcion:</strong>
                    <%= @cliente.descripcion %>
                  </p></td>

                   <td><p>
                    <strong>Fecha Inicio:</strong>
                    <%= @cliente.fechaInicio %>
                  </p></td>

                  <td><p>
                    <strong>Estado:</strong>
                    <%= @cliente.estado %>
                  </p></td>

               </tr>
              </tbody>
            </table>          
          </div>
      </div>
    </div>
  </div>