config/routes.rb
Rails.application.routes.draw do
  

   

  #resources :imprimir_lista
  resources :producto_puestos
  resources :guardias
  resources :puesto_puestos
  resources :turnos

  resources :presupuestooos do
      member do
        get 'imprimir'
    end
  end
  
  resources :categorias
  resources :productos
  resources :control_stock
  resources :stock
  
  resources :puestos do
            member do
            get 'pdf'
          end
        end

  resources :clientes
  
  resources :registro_clientes
  resources :reportes
  resources :presupuesto_creates
  resources :crea_presupuestos
  resources :crear_presupuestos
  
  resources :puesto_registros
  resources :guardia_registros
  resources :presupuestos
  resources :lista_calendarios
  resources :calendarios
  resources :registro_puestos

  get 'lista_puestos/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'guardias#index'

  post 'stock/incStock'

end

app/models/calendario.rb
class Calendario < ApplicationRecord
	validates :diasTrabajados, presence: true

	belongs_to :regis_guardium
	has_many :lista_calendario
	has_many :reporte
end

app/models/categoria.rb
class Categoria < ApplicationRecord
	has_many :productos 
end

app/models/cliente.rb
class Cliente < ApplicationRecord

	#validates :nombre, :num_ruc, :telefono, :direccion, presence: true

	has_many :puestos

	#has_many :reportes

	#paginacion
	self.per_page = 10
end

app/models/control_stock.rb
class ControlStock < ApplicationRecord
end

app/models/guardia.rb
class Guardia < ApplicationRecord
	has_many :puesto_puestos


	self.per_page = 10
end

app/models/presupuestooo.rb
class Presupuestooo < ApplicationRecord
	belongs_to :turno 
end

app/models/producto.rb
class Producto < ApplicationRecord
	belongs_to :categoria
	
	#belongs_to :puesto

	has_many :producto_puestos



end 

app/models/producto_puesto.rb
class ProductoPuesto < ApplicationRecord
	belongs_to :puesto
	belongs_to :producto
end

app/models/puesto.rb
class Puesto < ApplicationRecord
 
	
	#validates :direccion, :turno, :hora_entrada, :hora_salida, :cliente_id, :regis_guardium_id, presence: true


	belongs_to :cliente
	#belongs_to :regis_guardium


	has_many :reportes
	has_many :puesto_puestos
	accepts_nested_attributes_for  :puesto_puestos, allow_destroy: true
	
	has_many :producto_puestos
	accepts_nested_attributes_for  :producto_puestos, allow_destroy: true

	
	#Paginacion
	self.per_page = 10 
end

app/models/puesto_puesto.rb
class PuestoPuesto < ApplicationRecord
	belongs_to :puesto
	belongs_to :guardia
end

app/models/puesto_registro.rb
class PuestoRegistro < ApplicationRecord
	validates :puestoNombre, :direccion, :turno, :horaEntrada, :horaSalida, presence: true

	belongs_to :regis_guardium

	belongs_to :cliente
	has_many :calendario

	self.per_page = 10
end

app/models/regis_guardium.rb
class RegisGuardium < ApplicationRecord
	#validates :nombre, :apellido, :numDocumento, :direccion, :telefono,  presence: true
	

	#has_many :calendario
	
	has_many :puestos

	#has_many :reportes

	self.per_page = 10
end

app/models/registro_puesto.rb
class RegistroPuesto < ApplicationRecord
end

app/models/reporte.rb
class Reporte < ApplicationRecord
	#validates :horaEntrada, :horaSalida, :novedad, presence: true

	#belongs_to :calendario
	belongs_to :puesto
	#belongs_to :cliente
	#belongs_to :regis_guardia
end

app/models/stocks.rb
class Stocks < ApplicationRecord

	# 	validates :producto, :cantidad, :descripcion, presence: true
	#belongs_to :producto

end

app/models/turno.rb
class Turno < ApplicationRecord
	has_many :presupuestooos 
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
    #calcular cant de producto disponibles, despues de haber asignado
    #@disponible = (@producto.cantidad - @producto.puesto.cantidad)
    #@producto.cantidadDisponible = @disponible
    
  end

  # GET /productos/1
  # GET /productos/1.json
 def show
      @sumar = 0
      @producto.producto_puestos.each do |detalle|
      @sumar += detalle.cantidadAsignada 
      end

  end

  def sumar 

  end

  
  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json



  def create
    @producto = Producto.new(producto_params)
    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Se ha Creado.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      #@producto.cantidad = "cantidadTotalStock" 
     #@puesto.cantidad = "cantidadAsignado"
     #@restaStock = cantidadTotalStock - cantidadAsignado
     #@cantidadDisponible = @restaStock


      
      if @producto.update(producto_params)
         

        format.html { redirect_to @producto, notice: 'Se ha actualizado.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Se ha Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end
    def set_puesto
       @puesto = Puesto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nomProducto, :caracteristica, :categoria_id, :identificador, :cantidad)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/guardia_helper.rb
module GuardiaHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/puestos_helper.rb
module PuestosHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/productos/_form.html.erb
<%= form_with(model: producto, local: true) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
          <div class="col-xs-3">
          </div>
          <div class="jumbotron">
            <div class="container">
          <div class="col-xs-4">
              <form class="form-inline">

              <div class="field">
                    <%= form.label "Categoria" %>
                    <%= form.collection_select(:categoria_id, Categoria.all, :id, :nombre) %>
              </div><br><br>

              <div class="field">
                  <%= form.label :Identificador %>
                  <%= form.text_field :identificador, id: :producto_identificador %>
              </div><br><br>

              <div class="field">
                  <%= form.label :Nombre %>
                  <%= form.text_field :nomProducto, id: :producto_nomProducto %>
                </div><br><br>

          </div>
          <div class="col-xs-3">
          </div>
          <div class="col-xs-4">

                 <div class="field">
                  <%= form.label :Cantidad_Total%>
                  <%= form.number_field :cantidad, id: :producto_cantidad %>
                </div> <br><br>
                
                <div class="field">
                  <%= form.label :caracteristica %>
                  <%= form.text_area :caracteristica, id: :producto_caracteristica %>
                </div><br><br>
          </div>
          <div class="col-xs-3">
          </div>
      </div>
    </div>

        <div class="col-xs-3">
                <div class="actions">
                  <%= form.submit "Guardar", :class=>"button-guardar" %>
                </div>
              <% end %>
        </div>

app/views/productos/edit.html.erb
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
	        <div class="col-xs-3">

				<h2>Editar </h2><br><br>
			</div>
			<div class="col-xs-6">
			</div>
			<div class="col-xs-3">
				

				<%= link_to @producto, class: "btn btn-info" do %> <i class="glyphicon glyphicon-eye-open"></i>  Ver <% end %> |
				<%= link_to productos_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %> 
			</div>

			<%= render 'form', producto: @producto, class: "btn btn-info" do %>
				<% end %>

			</div>
	</div>
</div>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
        <div class="col-xs-3">
            <h2>Producto</h2><br><br><br>
        </div>
      
        <div class="col-xs-5">        
        </div>
        <div class="col-xs-3">

                      <%= link_to new_producto_path, class: 'btn btn-success' do %>
                    <i class="glyphicon glyphicon-calendar"></i> Nuevo Registro
                     <% end %>
        </div>
<div class="col-xs-12">
            <div class="jumbotron">
              <div class="container">
              <div class="row">
                <div class="col-xs-1">
                </div>
                <div class="col-xs-3">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                            <th>Categoria </th>
                            <th>Identificador </th>
                            <th>Nombre</th>
                            <th>Caracteristica</th>
                            <th>Cantidad Total</th>
                           <!-- <th>Cantidad Disponible</th> -->
                            <th colspan="3"></th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @productos.each do |producto| %>
                            <tr>
                              <td><%= producto.categoria.nombre %></td>
                              <td><%= producto.identificador %></td>
                              <td><%= producto.nomProducto %></td>
                              <td><%= producto.caracteristica %></td>
                              <td><%= producto.cantidad %></td>
                             
                              <td><%= link_to producto, class: 'btn btn-info' do %>
                                <i class="glyphicon glyphicon-eye-open"></i> Ver <% end %> 
                            </td>
                            
                             <td><%= link_to edit_producto_path(producto), class: 'btn btn-info' do %>
                              <i class="glyphicon glyphicon-edit"></i> Editar <% end %>
                            </td>

                              <td><%= link_to producto, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-primary' do %>
                                    <i class="glyphicon glyphicon-trash"></i> Eliminar <% end %>
                            </td>
                            </tr>
                              <% end %>
                            </tbody>
                      </table>
                    </div>               

                  </div>
              </div>
            </div>
          </div>

          

           <div class="col-xs-5">
          </div>

app/views/productos/new.html.erb
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
	        <div class="col-xs-3">

				<h2>Nuevo Producto</h2><br><br><br>

			</div>
		</div>
				<%= render 'form', producto: @producto %>

		<div class="col-xs-5">
        </div>
        <div class="col-xs-4">


				<%= link_to productos_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %>
		</div>
		</div>
</div>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>
<div id="main-container" class="container">
      <div class="row"><br><br>
      <div class="col-xs-12">
          <div class="col-xs-6">
          </div>

          <div class="col-xs-6">
				<%= link_to edit_producto_path(@producto), class: "btn btn-info" do %><i class="glyphicon glyphicon-pencil"></i> Editar <% end %> |
				<%= link_to productos_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %>         		

          </div>
          <br><br><br><br>
          <div class="col-xs-10">
            <table class="table table-striped">

          <td><p>
					  <strong>Categoria:</strong>
					  <%= @producto.categoria.nombre %>
					</p></td>

          <td><p>
            <strong>Identificador:</strong>
            <%= @producto.identificador %>
          </p></td>

					<td><p>
					  <strong>Nombre Producto:</strong>
					  <%= @producto.nomProducto %>
					</p></td>

					<td><p>
					  <strong>Caracteristica:</strong>
					  <%= @producto.caracteristica %>
					</p></td>

          <td><p>
            <strong>Cantidad Total:</strong>
            <%= @producto.cantidad %>
          </p></td>

          <td><p>
            <strong>Cantidad Asignado:</strong>
               <%= @sumar %>
          </p></td>

          <td><p>
            <strong>Cantidad Disponible:</strong>
            <%= @producto.cantidad - @sumar %>
             
          </p></td>

			</tr>
              </tbody>
            </table>          
          </div>
      </div>
    </div>
  </div>