config/routes.rb
Rails.application.routes.draw do
  

   

  #resources :imprimir_lista
  resources :producto_puestos
  resources :guardias
  resources :puesto_puestos
  resources :turnos

  resources :presupuestooos do
      member do
        get 'imprimir'
    end
  end
  
  resources :categorias
  resources :productos
  resources :control_stock
  resources :stock
  
  resources :puestos do
            member do
            get 'pdf'
          end
        end

  resources :clientes
  
  resources :registro_clientes
  resources :reportes
  resources :presupuesto_creates
  resources :crea_presupuestos
  resources :crear_presupuestos
  
  resources :puesto_registros
  resources :guardia_registros
  resources :presupuestos
  resources :lista_calendarios
  resources :calendarios
  resources :registro_puestos

  get 'lista_puestos/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'guardias#index'

  post 'stock/incStock'

end

app/models/calendario.rb
class Calendario < ApplicationRecord
	validates :diasTrabajados, presence: true

	belongs_to :regis_guardium
	has_many :lista_calendario
	has_many :reporte
end

app/models/categoria.rb
class Categoria < ApplicationRecord
	has_many :productos 
end

app/models/cliente.rb
class Cliente < ApplicationRecord

	#validates :nombre, :num_ruc, :telefono, :direccion, presence: true

	has_many :puestos

	#has_many :reportes

	#paginacion
	self.per_page = 10
end

app/models/control_stock.rb
class ControlStock < ApplicationRecord
end

app/models/guardia.rb
class Guardia < ApplicationRecord
	has_many :puesto_puestos


	self.per_page = 10
end

app/models/presupuestooo.rb
class Presupuestooo < ApplicationRecord
	belongs_to :turno 
end

app/models/producto.rb
class Producto < ApplicationRecord
	belongs_to :categoria
	
	#belongs_to :puesto

	has_many :producto_puestos



end 

app/models/producto_puesto.rb
class ProductoPuesto < ApplicationRecord
	belongs_to :puesto
	belongs_to :producto
end

app/models/puesto.rb
class Puesto < ApplicationRecord
 
	
	#validates :direccion, :turno, :hora_entrada, :hora_salida, :cliente_id, :regis_guardium_id, presence: true


	belongs_to :cliente
	#belongs_to :regis_guardium


	has_many :reportes
	has_many :puesto_puestos
	accepts_nested_attributes_for  :puesto_puestos, allow_destroy: true
	
	has_many :producto_puestos
	accepts_nested_attributes_for  :producto_puestos, allow_destroy: true

	
	#Paginacion
	self.per_page = 10 
end

app/models/puesto_puesto.rb
class PuestoPuesto < ApplicationRecord
	belongs_to :puesto
	belongs_to :guardia
end

app/models/puesto_registro.rb
class PuestoRegistro < ApplicationRecord
	validates :puestoNombre, :direccion, :turno, :horaEntrada, :horaSalida, presence: true

	belongs_to :regis_guardium

	belongs_to :cliente
	has_many :calendario

	self.per_page = 10
end

app/models/regis_guardium.rb
class RegisGuardium < ApplicationRecord
	#validates :nombre, :apellido, :numDocumento, :direccion, :telefono,  presence: true
	

	#has_many :calendario
	
	has_many :puestos

	#has_many :reportes

	self.per_page = 10
end

app/models/registro_puesto.rb
class RegistroPuesto < ApplicationRecord
end

app/models/reporte.rb
class Reporte < ApplicationRecord
	#validates :horaEntrada, :horaSalida, :novedad, presence: true

	#belongs_to :calendario
	belongs_to :puesto
	#belongs_to :cliente
	#belongs_to :regis_guardia
end

app/models/stocks.rb
class Stocks < ApplicationRecord

	# 	validates :producto, :cantidad, :descripcion, presence: true
	#belongs_to :producto

end

app/models/turno.rb
class Turno < ApplicationRecord
	has_many :presupuestooos 
end

app/controllers/puesto_puestos_controller.rb
class PuestoPuestosController < ApplicationController
  before_action :set_puesto_puesto, only: [:show, :edit, :update, :destroy]

  # GET /puesto_puestos
  # GET /puesto_puestos.json
  def index
    @puesto_puestos = PuestoPuesto.all
  end

  # GET /puesto_puestos/1
  # GET /puesto_puestos/1.json
  def show
  end

  # GET /puesto_puestos/new
  def new
    @puesto_puesto = PuestoPuesto.new
  end

  # GET /puesto_puestos/1/edit
  def edit
  end

  # POST /puesto_puestos
  # POST /puesto_puestos.json
  def create
    @puesto_puesto = PuestoPuesto.new(puesto_puesto_params)

    respond_to do |format|
      if @puesto_puesto.save
        format.html { redirect_to @puesto_puesto, notice: 'Puesto puesto was successfully created.' }
        format.json { render :show, status: :created, location: @puesto_puesto }
      else
        format.html { render :new }
        format.json { render json: @puesto_puesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puesto_puestos/1
  # PATCH/PUT /puesto_puestos/1.json
  def update
    respond_to do |format|
      if @puesto_puesto.update(puesto_puesto_params)
        format.html { redirect_to @puesto_puesto, notice: 'Puesto puesto was successfully updated.' }
        format.json { render :show, status: :ok, location: @puesto_puesto }
      else
        format.html { render :edit }
        format.json { render json: @puesto_puesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puesto_puestos/1
  # DELETE /puesto_puestos/1.json
  def destroy
    @puesto_puesto.destroy
    respond_to do |format|
      format.html { redirect_to puesto_puestos_url, notice: 'Puesto puesto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puesto_puesto
      @puesto_puesto = PuestoPuesto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puesto_puesto_params
      params.require(:puesto_puesto).permit(:puesto_id, :guardia_id)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/guardia_helper.rb
module GuardiaHelper
end

app/helpers/puesto_puestos_helper.rb
module PuestoPuestosHelper
end

app/helpers/puestos_helper.rb
module PuestosHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/puesto_puestos/_form.html.erb
<%= form_with(model: puesto_puesto, local: true) do |form| %>
  <% if puesto_puesto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(puesto_puesto.errors.count, "error") %> prohibited this puesto_puesto from being saved:</h2>

      <ul>
      <% puesto_puesto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/puesto_puestos/edit.html.erb
<h1>Editing Puesto Puesto</h1>

<%= render 'form', puesto_puesto: @puesto_puesto %>

<%= link_to 'Show', @puesto_puesto %> |
<%= link_to 'Back', puesto_puestos_path %>

app/views/puesto_puestos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Puesto Puestos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puesto_puestos.each do |puesto_puesto| %>
      <tr>
        <td><%= link_to 'Show', puesto_puesto %></td>
        <td><%= link_to 'Edit', edit_puesto_puesto_path(puesto_puesto) %></td>
        <td><%= link_to 'Destroy', puesto_puesto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puesto Puesto', new_puesto_puesto_path %>

app/views/puesto_puestos/new.html.erb
<h1>New Puesto Puesto</h1>

<%= render 'form', puesto_puesto: @puesto_puesto %>

<%= link_to 'Back', puesto_puestos_path %>

app/views/puesto_puestos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_puesto_puesto_path(@puesto_puesto) %> |
<%= link_to 'Back', puesto_puestos_path %>