config/routes.rb
Rails.application.routes.draw do
  

   

  #resources :imprimir_lista
  resources :producto_puestos
  resources :guardias
  resources :puesto_puestos
  resources :turnos

  resources :presupuestooos do
      member do
        get 'imprimir'
    end
  end
  
  resources :categorias
  resources :productos
  resources :control_stock
  resources :stock
  
  resources :puestos do
            member do
            get 'pdf'
          end
        end

  resources :clientes
  
  resources :registro_clientes
  resources :reportes
  resources :presupuesto_creates
  resources :crea_presupuestos
  resources :crear_presupuestos
  
  resources :puesto_registros
  resources :guardia_registros
  resources :presupuestos
  resources :lista_calendarios
  resources :calendarios
  resources :registro_puestos

  get 'lista_puestos/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'guardias#index'

  post 'stock/incStock'

end

app/models/calendario.rb
class Calendario < ApplicationRecord
	validates :diasTrabajados, presence: true

	belongs_to :regis_guardium
	has_many :lista_calendario
	has_many :reporte
end

app/models/categoria.rb
class Categoria < ApplicationRecord
	has_many :productos 
end

app/models/cliente.rb
class Cliente < ApplicationRecord

	#validates :nombre, :num_ruc, :telefono, :direccion, presence: true

	has_many :puestos

	#has_many :reportes

	#paginacion
	self.per_page = 10
end

app/models/control_stock.rb
class ControlStock < ApplicationRecord
end

app/models/guardia.rb
class Guardia < ApplicationRecord
	has_many :puesto_puestos


	self.per_page = 10
end

app/models/presupuestooo.rb
class Presupuestooo < ApplicationRecord
	belongs_to :turno 
end

app/models/producto.rb
class Producto < ApplicationRecord
	belongs_to :categoria
	
	#belongs_to :puesto

	has_many :producto_puestos



end 

app/models/producto_puesto.rb
class ProductoPuesto < ApplicationRecord
	belongs_to :puesto
	belongs_to :producto
end

app/models/puesto.rb
class Puesto < ApplicationRecord
 
	
	#validates :direccion, :turno, :hora_entrada, :hora_salida, :cliente_id, :regis_guardium_id, presence: true


	belongs_to :cliente
	#belongs_to :regis_guardium


	has_many :reportes
	has_many :puesto_puestos
	accepts_nested_attributes_for  :puesto_puestos, allow_destroy: true
	
	has_many :producto_puestos
	accepts_nested_attributes_for  :producto_puestos, allow_destroy: true

	
	#Paginacion
	self.per_page = 10 
end

app/models/puesto_puesto.rb
class PuestoPuesto < ApplicationRecord
	belongs_to :puesto
	belongs_to :guardia
end

app/models/puesto_registro.rb
class PuestoRegistro < ApplicationRecord
	validates :puestoNombre, :direccion, :turno, :horaEntrada, :horaSalida, presence: true

	belongs_to :regis_guardium

	belongs_to :cliente
	has_many :calendario

	self.per_page = 10
end

app/models/regis_guardium.rb
class RegisGuardium < ApplicationRecord
	#validates :nombre, :apellido, :numDocumento, :direccion, :telefono,  presence: true
	

	#has_many :calendario
	
	has_many :puestos

	#has_many :reportes

	self.per_page = 10
end

app/models/registro_puesto.rb
class RegistroPuesto < ApplicationRecord
end

app/models/reporte.rb
class Reporte < ApplicationRecord
	#validates :horaEntrada, :horaSalida, :novedad, presence: true

	#belongs_to :calendario
	belongs_to :puesto
	#belongs_to :cliente
	#belongs_to :regis_guardia
end

app/models/stocks.rb
class Stocks < ApplicationRecord

	# 	validates :producto, :cantidad, :descripcion, presence: true
	#belongs_to :producto

end

app/models/turno.rb
class Turno < ApplicationRecord
	has_many :presupuestooos 
end

app/controllers/puesto_registros_controller.rb
class PuestoRegistrosController < ApplicationController
  before_action :set_puesto_registro, only: [:show, :edit, :update, :destroy]

  # GET /puesto_registros
  # GET /puesto_registros.json
  def index
    if params[:search].nil? 
        @puesto_registros = PuestoRegistro.all
    else
      @puesto_registros =  PuestoRegistro.where("puestoNombre LIKE ?", "%#{params["search"]}%")
      #Cliente.where("cliente LIKE ? = '#{params["search"]}'")
    end     
  end
  # GET /puesto_registros/1
  # GET /puesto_registros/1.json
  def show
  end

  # GET /puesto_registros/new
  def new
    @puesto_registro = PuestoRegistro.new
  end

  # GET /puesto_registros/1/edit
  def edit
  end

  # POST /puesto_registros
  # POST /puesto_registros.json
  def create
    @puesto_registro = PuestoRegistro.new( puesto_registro_params)

    respond_to do |format|
      if @puesto_registro.save
        format.html { redirect_to @puesto_registro, notice: 'Se ha creado.' }
        format.json { render :show, status: :created, location: @puesto_registro }
      else
        format.html { render :new }
        format.json { render json: @puesto_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puesto_registros/1
  # PATCH/PUT /puesto_registros/1.json
  def update
    respond_to do |format|
      if @puesto_registro.update(puesto_registro_params)
        format.html { redirect_to @puesto_registro, notice: 'Se Actualizo.' }
        format.json { render :show, status: :ok, location: @puesto_registro }
      else
        format.html { render :edit }
        format.json { render json: @puesto_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puesto_registros/1
  # DELETE /puesto_registros/1.json
  def destroy
    @puesto_registro.destroy
    respond_to do |format|
      format.html { redirect_to puesto_registros_url, notice: 'Se ha Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puesto_registro
      @puesto_registro = PuestoRegistro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puesto_registro_params
      params.require(:puesto_registro).permit(:puestoNombre, :direccion, :turno, :regis_guardium_id,:horaEntrada, :horaSalida)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/guardia_helper.rb
module GuardiaHelper
end

app/helpers/puesto_registros_helper.rb
module PuestoRegistrosHelper
end

app/helpers/puestos_helper.rb
module PuestosHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/puesto_registros/_form.html.erb
<%= form_with(model: puesto_registro, local: true) do |form| %>
  <% if puesto_registro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(puesto_registro.errors.count, "error") %> prohibited this puesto_registro from being saved:</h2>

      <ul>
      <% puesto_registro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
          <div class="col-xs-4">
          </div>
          <div class="jumbotron">
            <div class="container">
          <div class="col-xs-5">
                <form class="form-inline">

                 
                  Puesto
                   <div class="field">
                    <%= form.collection_select(:clientes_id, Cliente.all, :id, :cliente, :class=>"form-control input-sm") %><br><br>
                  </div>

                  <div class="field">
                    <%= form.text_field :direccion, id: :puesto_registro_direccion, class: "form-control", placeholder: "Direccion" %><br><br> 
                  </div>

              <div class="field">
                    <%= form.text_field :turno, id: :puesto_registro_turno, class:"form-control", placeholder:"Turno" %><br><br> 
                  </div>
                        </div>
          <div class="col-xs-2">
          </div>
          <div class="col-xs-4">

                  Guardia
                  <div class="field">
                    <%= form.collection_select(:regis_guardium_id, RegisGuardium.all, :id, :nombre, :class=>"form-control input-sm") %><br><br>
                  </div>

                  Hora Entrada
                  <div class="field"> 
                    <%= form.time_select :horaEntrada, id: :puesto_registro_horaEntrada, class:"form-control"%> <br><br> 
                  </div>

                  Hora Salida
                  <div class="field">
                    <%= form.time_select :horaSalida, id: :puesto_registro_horaSalida, class:"form-control" %>
                  </div>
          </div>
          <div class="col-xs-2">
          </div>
          <div class="col-xs-3">
          </div>
          </div>
          </div>

     <div class="col-xs-3">
        <div class="actions">
            <%= form.submit "Guardar", :class => "button-guardar"  %>
        </div>
        <% end %>
    </div>

app/views/puesto_registros/edit.html.erb
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
	        <div class="col-xs-3">
				<h1>Editar Puesto </h1>
			</div>
			<div class="col-xs-6">
			</div>
			<div class="col-xs-3">
				
				<%= link_to @puesto_registro, class: "btn btn-info" do %> <i class="glyphicon glyphicon-eye-open"></i>  Ver <% end %> |
				<%= link_to puesto_registros_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %> 
			</div>

			<%= render 'form', puesto_registro: @puesto_registro, class: "btn btn-info" do %>
			<% end %>

			</div>
		</div>
</div>

app/views/puesto_registros/index.html.erb
<p id="notice"><%= notice %></p>
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
        <div class="col-xs-3">
                <h2>Registrar Puesto </h2><br><br><br>
        </div>
        <div class="col-xs-5">
        </div>
        <div class="col-xs-4">
            <%= form_tag puesto_registros_path, :method => 'get' do %>
                <p>
                  <%= text_field_tag :search, params[:search] %>
                  <%= submit_tag "Buscar", :name => nil %>
                </p>
            <% end %>
        </div>

          <div class="col-xs-12">
            <div class="jumbotron">
              <div class="container">
              <div class="row">
                <div class="col-xs-1">
                </div>
                <div class="col-xs-3">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Puesto</th>
                          <th>Direccion</th>
                          <th>Guardia</th>
                          <th>Turno</th>
                          <th>Hora Entrada</th>
                          <th>Hora Salida</th>
                          <th></th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @puesto_registros.each do |puesto_registro| %>
                          <tr>
                            <td><%= puesto_registro.puestoNombre %></td>
                            <td><%= puesto_registro.direccion %></td>
                            <td></td>
                            <td><%= puesto_registro.turno %></td>
                            <td><%= puesto_registro.horaEntrada %></td>
                            <td><%= puesto_registro.horaSalida %></td>
                             <td><%= link_to Calendario %></td>


                            <td><%= link_to puesto_registro, class: 'btn btn-info' do %>
                                    <i class="glyphicon glyphicon-eye-open"></i> Ver
                                    <% end %> 
                            </td>

                            <td><%= link_to edit_puesto_registro_path(puesto_registro), class: 'btn btn-info' do %>
                                    <i class="glyphicon glyphicon-edit"></i> Editar <% end %>
                            </td>

                            <td><%= link_to puesto_registro, method: :delete, data: { confirm: 'Estas Seguro?' }, class: 'btn btn-primary' do %>
                                    <i class="glyphicon glyphicon-trash"></i> Eliminar <% end %>
                            </td>

                        </tr>
                              <% end %>
                            </tbody>
                      </table>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        <div class="col-xs-3">
          <%= link_to new_puesto_registro_path, class: 'btn btn-success' do %>
          <i class="glyphicon glyphicon-user"></i> Nuevo Registro
          <% end %>
        </div>
        <div class="col-xs-5">
        </div>
        
</div>

</div>
</div>
</div>

                

app/views/puesto_registros/new.html.erb
<div id="main-container" class="container">
      <div class="row">
      <div class="col-xs-12">
	        <div class="col-xs-3">
					<h1>Nuevo Registro de Puesto</h1><br><br><br>

			</div>
		</div>

			
	  
 			<%= render 'form', puesto_registro: @puesto_registro %>
		
		<div class="col-xs-5">
        </div>
        <div class="col-xs-4">
				<%= link_to puesto_registros_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %>
		
		</div>
		</div>
</div>

app/views/puesto_registros/show.html.erb
<p id="notice"><%= notice %></p>
<div id="main-container" class="container">
      <div class="row"><br><br>
      <div class="col-xs-12">
          <div class="col-xs-6">
          </div>

          <div class="col-xs-6">
                  <%= link_to edit_puesto_registro_path(@puesto_registro), class: "btn btn-info" do %><i class="glyphicon glyphicon-pencil"></i> Editar <% end %> |
                  <%= link_to puesto_registros_path, class: "btn btn-default"  do %><i class="glyphicon glyphicon-arrow-left"></i> Atras <% end %>
          </div>
          <br><br><br><br>
          <div class="col-xs-10">
            <table class="table table-striped">

              <tbody>
                <tr>
                      <td><p>
                        <strong>Puestonombre:</strong>
                        <%= @puesto_registro.puestoNombre %>
                      </p></td>

                      <td><p>
                        <strong>Direccion:</strong>
                        <%= @puesto_registro.direccion %>
                      </p></td>

                      <td><p>
                        <strong>Turno:</strong>
                        <%= @puesto_registro.turno %>
                      </p></td>

                      <td><p>
                        <strong>Horaentrada:</strong>
                        <%= @puesto_registro.horaEntrada %>
                      </p></td>

                      <td><p>
                        <strong>Horasalida:</strong>
                        <%= @puesto_registro.horaSalida %>
                      </p></td>

                  </tr>
              </tbody>
            </table>          
          </div>
      </div>
    </div>
  </div>